version: '3.1'
services:
  webserverphp:
    build: ./docker/php/
    restart: always
    ports:
      - 8080:80
    depends_on: [db]
    volumes:
      - ./src:/var/www/html

  db:
    image: mariadb:10.5.3
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: anarcociclista
      MYSQL_PASSWORD: strongpassword
      MYSQL_RANDOM_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on: [db]
    links:
      - db
    ports:
      - 8181:80
    environment:
        MYSQL__USERNAME: root
        MYSQL_ROOT_PASSWORD: root
        PMA_ARBITRARY: 1
        PMA_USER: anarcociclista
        PMA_PASSWORD: strongpassword
        PMA_HOST: db
        PMA_PORT: 3306
volumes:
  db: