version: '3.1'
services:
  webserver:
    build: ./docker/php/
    restart: always
    ports:
      - 8080:80
    depends_on: [db]
    volumes:
      - ./src:/var/www/html

  db:
    image: mariadb:10.5.3
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: anarcociclista
      MYSQL_PASSWORD: strongpassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: